### PR TITLE
Publish HistomicsDetect to PyPI as histomics_detect

### PR DESCRIPTION
**Pull request by Leengit**
- Change occurrences of the old `CancerDataScience/histomics_detect` repository name to `DigitalSlideArchive/HistomicsDetect`
- Remove `setup.py` in favor of an expanded `pyproject.toml` and a new `histomics_detect/__init__.py`
- Install new `.github/workflows/build-test-package.yml` to submit the package to PyPI when a "new release" is made via GitHub.  

N.B. Ordinary pull requests and merges will not publish to PyPI. 
N.B. Be sure to update the `__version__` variable in  `histomics_detect/__init__.py` and merge the update prior to creating the new release via GitHub.

### CODE REVIEW

**Comment by Leengit** [comment]
@cooperlab, is it okay if I merge this and then publish `histomics_detect` version `0.0.1` to the public?

**Comment by cooperlab** [comment]
> @cooperlab, is it okay if I merge this and then publish `histomics_detect` version `0.0.1` to the public?

Yes.

**Comment by Leengit** [comment]
The GitHub release successfully triggered the publishing to PyPI.  The command
```sh
pip install histomics_detect
```
will now fetch and install version `0.0.1`.

**Comment by cooperlab** [comment]
Thank you, @Leengit

**Pull request merged**
